#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';

const repoRoot = process.cwd();
const inputPath = path.join(repoRoot, 'prebuilt_cache.json');
const outputPath = path.join(repoRoot, 'src', 'databanks_imported.ts');

const BATCH_SIZE = 250;

const STOPWORDS = new Set([
  'a','an','and','the','to','of','for','with','in','on','at','by','from','into','through','over','under','after','before','is','are','was','were','be','been','being','that','this','these','those','it','its','their','his','her','as','or','but','than','then','so','if','while','during'
]);

function normalizeSpaces(value) {
  return value.replace(/\s+/g, ' ').trim();
}

function normalizeTrait(value) {
  let v = normalizeSpaces(value);
  v = v.replace(/[\[\]!]/g, '');
  v = v.replace(/\s*,\s*/g, ', ');
  v = v.replace(/\.+$/g, '');
  v = v.toLowerCase();
  return normalizeSpaces(v);
}

function sentenceCase(value) {
  if (!value) return value;
  return value[0].toUpperCase() + value.slice(1);
}

function normalizeSecret(value) {
  let v = normalizeSpaces(value);
  v = v.replace(/[\[\]!]/g, '');
  v = v.replace(/\s+([,.;:!?])/g, '$1');
  v = v.replace(/[.]{2,}/g, '.');
  v = v.replace(/\.+$/g, '');
  v = v.toLowerCase();
  v = sentenceCase(v);
  return normalizeSpaces(v);
}

function stemToken(t) {
  if (t.endsWith('ing') && t.length > 5) return t.slice(0, -3);
  if (t.endsWith('ed') && t.length > 4) return t.slice(0, -2);
  if (t.endsWith('es') && t.length > 4) return t.slice(0, -2);
  if (t.endsWith('s') && t.length > 3) return t.slice(0, -1);
  return t;
}

function tokensForSimilarity(value) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9'\s]/g, ' ')
    .split(/\s+/)
    .filter(Boolean)
    .map(stemToken)
    .filter((t) => !STOPWORDS.has(t));
}

function jaccard(a, b) {
  if (a.size === 0 && b.size === 0) return 1;
  let intersection = 0;
  for (const item of a) {
    if (b.has(item)) intersection++;
  }
  const union = a.size + b.size - intersection;
  return union === 0 ? 0 : intersection / union;
}

function isLikelyBoring(value, kind) {
  const len = value.length;
  if (kind === 'traits') {
    if (len < 12 || len > 96) return true;
    const commaCount = (value.match(/,/g) || []).length;
    if (commaCount < 2 || commaCount > 4) return true;
    return false;
  }
  if (len < 12 || len > 140) return true;
  const lettersOnly = value.toLowerCase().replace(/[^a-z]/g, '');
  if (lettersOnly.length < 8) return true;
  return false;
}

function curateList(items, kind) {
  const kept = [];
  const seenNormalized = new Set();
  const tokenSets = [];

  for (let i = 0; i < items.length; i += BATCH_SIZE) {
    const chunk = items.slice(i, i + BATCH_SIZE);

    for (const raw of chunk) {
      if (typeof raw !== 'string') continue;
      const normalized =
        kind === 'traits' ? normalizeTrait(raw) : normalizeSecret(raw);
      if (!normalized) continue;
      if (isLikelyBoring(normalized, kind)) continue;
      if (seenNormalized.has(normalized)) continue;

      const tks = new Set(tokensForSimilarity(normalized));
      let nearDup = false;
      for (let idx = 0; idx < tokenSets.length; idx++) {
        const sim = jaccard(tks, tokenSets[idx]);
        if (sim >= 0.84) {
          nearDup = true;
          break;
        }
      }
      if (nearDup) continue;

      seenNormalized.add(normalized);
      tokenSets.push(tks);
      kept.push(normalized);
    }
  }

  return kept;
}

function toTsArray(items) {
  return items.map((v) => `  ${JSON.stringify(v)},`).join('\n');
}

function main() {
  const raw = fs.readFileSync(inputPath, 'utf8');
  const json = JSON.parse(raw);

  const traitInput = Array.isArray(json.traits) ? json.traits : [];
  const normalInput = Array.isArray(json.normalSecrets) ? json.normalSecrets : [];
  const supernaturalInput = Array.isArray(json.supernaturalSecrets)
    ? json.supernaturalSecrets
    : [];

  const curatedTraits = curateList(traitInput, 'traits');
  const curatedNormal = curateList(normalInput, 'normal');
  const curatedSupernatural = curateList(supernaturalInput, 'supernatural');

  const file = `// Auto-generated by scripts/curate_prebuilt_cache.mjs\n// Source: prebuilt_cache.json\n// Normalized + deduped + near-duplicate pruned in bounded batches.\n\nexport const IMPORTED_TRAIT_BANK = [\n${toTsArray(curatedTraits)}\n];\n\nexport const IMPORTED_NORMAL_SECRET_BANK = [\n${toTsArray(curatedNormal)}\n];\n\nexport const IMPORTED_SUPERNATURAL_SECRET_BANK = [\n${toTsArray(curatedSupernatural)}\n];\n`;

  fs.writeFileSync(outputPath, file);

  console.log('curation complete');
  console.log('traits:', traitInput.length, '=>', curatedTraits.length);
  console.log('normalSecrets:', normalInput.length, '=>', curatedNormal.length);
  console.log('supernaturalSecrets:', supernaturalInput.length, '=>', curatedSupernatural.length);
  console.log('wrote', path.relative(repoRoot, outputPath));
}

main();
