export const cthulhuData = {
  firstNamesMale: [
    "Clarence",
    "Howard",
    "Norman",
    "Everett",
    "Marvin",
    "Milton",
    "Virgil",
    "Glenn",
    "Cecil",
    "Warren",
    "Horace",
    "Melvin",
    "Gilbert",
    "Arnold",
    "Perry",
    "Vernon",
    "Gerald",
    "Isaac",
    "Irving",
    "Sidney",
    "Willard",
    "Wallace",
    "Maurice",
    "Wesley",
    "Gordon",
    "Kenneth",
    "Harley",
    "Rufus",
    "Emmett",
    "Clayton",
    "Orville",
    "Lonnie",
    "Curtis",
    "Nelson",
    "Simon",
    "Alonzo",
    "Calvin",
    "Wilbur",
    "Elbert",
    "Ambrose",
    "Roscoe",
    "Hubert",
    "Noah",
    "Morris",
    "Cornelius",
    "Clifton",
    "Sylvester",
    "Reuben",
    "Ellis",
    "August",
    "Donald",
    "John",
    "William",
    "James",
    "George",
    "Charles",
    "Joseph",
    "Frank",
    "Robert",
    "Edward",
    "Henry",
    "Harry",
    "Thomas",
    "Walter",
    "Arthur",
    "Fred",
    "Albert",
    "Willie",
    "Roy",
    "Louis",
    "Earl",
    "Paul",
    "Carl",
    "Ernest",
    "Samuel",
    "Raymond",
    "Richard",
    "Joe",
    "David",
    "Charlie",
    "Harold",
    "Ralph",
    "Andrew",
    "Herbert",
    "Elmer",
    "Oscar",
    "Jesse",
    "Alfred",
    "Will",
    "Daniel",
    "Sam",
    "Leo",
    "Jack",
    "Lawrence",
    "Francis",
    "Benjamin",
    "Lee",
    "Eugene",
    "Herman",
    "Peter",
    "Frederick",
    "Floyd",
    "Michael",
    "Ray",
    "Lewis",
    "Claude",
    "Clyde",
    "Edwin",
    "Tom",
    "Martin",
    "Leonard",
    "Ben",
    "Chester",
    "Edgar",
    "Jim",
    "Harvey",
    "Russell",
    "Lester",
    "Clifford",
    "Luther",
    "Homer",
    "Jacob",
    "Leroy",
    "Otto",
    "Guy",
    "Lloyd",
    "Anthony",
    "Jessie",
    "Hugh",
    "Ed",
    "Bernard",
    "Theodore",
    "Stanley",
    "Eddie",
    "Patrick",
    "Philip",
    "Leon",
    "Archie",
    "Leslie",
    "Oliver",
    "Allen",
    "Alexander",
  ],
  firstNamesFemale: [
    "Abigail",
    "Adelaide",
    "Adeline",
    "Agatha",
    "Alberta",
    "Alfreda",
    "Alma",
    "Amanda",
    "Amelia",
    "Anastasia",
    "Angelina",
    "Ann",
    "Anna Mae",
    "Anne",
    "Antonia",
    "Augusta",
    "Beulah",
    "Bettie",
    "Bessie Mae",
    "Blanche",
    "Bridget",
    "Camilla",
    "Caroline",
    "Cecilia",
    "Charlotte",
    "Christine",
    "Clara Belle",
    "Clarissa",
    "Constance",
    "Cynthia",
    "Dorothea",
    "Edwina",
    "Eleanor",
    "Elinor",
    "Eliza",
    "Elizabeth Ann",
    "Ella Mae",
    "Ellen",
    "Elmira",
    "Emeline",
    "Emilia",
    "Emilie",
    "Etta",
    "Eugenia",
    "Evangeline",
    "Flora",
    "Frida",
    "Georgiana",
    "Geraldine",
    "Gertrude Mae",
    "Gwendolyn",
    "Harriet",
    "Henrietta",
    "Hilda",
    "Inez",
    "Isabel",
    "Isabelle",
    "Josephina",
    "Kathleen",
    "Leona",
    "Letha",
    "Letitia",
    "Lorena",
    "Loretta",
    "Lucile",
    "Lucinda",
    "Luella",
    "Maggie Mae",
    "Margie",
    "Marguerite Ann",
    "Marietta",
    "Martha Lee",
    "Matilda",
    "Maureen",
    "Maybelle",
    "Mazie",
    "Mercedes",
    "Millicent",
    "Minnie Lee",
    "Muriel",
    "Myra",
    "Naomi",
    "Nell",
    "Nina",
    "Nola",
    "Ophelia",
    "Paulina",
    "Phoebe",
    "Rebecca",
    "Rena",
    "Roberta",
    "Rosalie",
    "Rosamond",
    "Rowena",
    "Sabina",
    "Selma",
    "Serena",
    "Sibyl",
    "Sophia",
    "Sylvia",
    "Theresa",
    "Therese",
    "Tillie",
    "Una",
    "Valeria",
    "Vera Mae",
    "Veronica",
    "Victoria",
    "Violet",
    "Virginia Mae",
    "Wilhelmina",
    "Willa",
    "Winifred",
    "Zora",
    "Mary",
    "Anna",
    "Margaret",
    "Helen",
    "Elizabeth",
    "Ruth",
    "Florence",
    "Ethel",
    "Emma",
    "Marie",
    "Clara",
    "Bertha",
    "Minnie",
    "Bessie",
    "Alice",
    "Lillian",
    "Edna",
    "Grace",
    "Annie",
    "Mabel",
    "Ida",
    "Rose",
    "Hazel",
    "Gertrude",
    "Martha",
    "Pearl",
    "Frances",
    "Myrtle",
    "Edith",
    "Nellie",
    "Sarah",
    "Ella",
    "Eva",
    "Laura",
    "Elsie",
    "Louise",
    "Esther",
    "Catherine",
    "Agnes",
    "Carrie",
    "Lillie",
    "Mildred",
    "Gladys",
    "Irene",
    "Julia",
    "Hattie",
    "Cora",
    "Lena",
    "Josephine",
    "Mattie",
    "Jennie",
    "Jessie",
    "Maude",
    "Mae",
    "Dorothy",
    "Ada",
    "Lucy",
    "Lula",
    "Mamie",
    "Fannie",
    "Stella",
    "Katherine",
    "Viola",
    "Ruby",
    "Dora",
    "Maggie",
    "Nora",
    "Rosa",
    "Beatrice",
    "Sadie",
    "Marion",
    "Willie",
    "Effie",
    "May",
    "Pauline",
    "Nettie",
    "Susie",
    "Della",
    "Vera",
    "Marguerite",
    "Daisy",
    "Lydia",
    "Virginia",
    "Olive",
    "Kathryn",
    "Evelyn",
  ],
  lastNames: [
    "Henderson",
    "Flores",
    "Gonzalez",
    "Bryant",
    "Alexander",
    "Russell",
    "Griffin",
    "Diaz",
    "Hayes",
    "Myers",
    "Ford",
    "Hamilton",
    "Graham",
    "Simmons",
    "Patterson",
    "Jordan",
    "Reynolds",
    "Fisher",
    "Ellis",
    "Harrison",
    "Gibson",
    "McDonald",
    "Cruz",
    "Marshall",
    "Ortiz",
    "Gomez",
    "Murray",
    "Freeman",
    "Wells",
    "Webb",
    "Simpson",
    "Stevens",
    "Tucker",
    "Porter",
    "Hunter",
    "Hicks",
    "Crawford",
    "Henry",
    "Boyd",
    "Mason",
    "Morales",
    "Kenneth",
    "Warren",
    "Dixon",
    "Ramos",
    "Reyes",
    "Burns",
    "Gordon",
    "Shaw",
    "Holmes",
    "Rice",
    "Robertson",
    "Hunt",
    "Black",
    "Daniels",
    "Palmer",
    "Mills",
    "Nichols",
    "Grant",
    "Knight",
    "Ferguson",
    "Stone",
    "Hawkins",
    "Dunn",
    "Perkins",
    "Hudson",
    "Spencer",
    "Gardner",
    "Stephens",
    "Payne",
    "Pierce",
    "Berry",
    "Matthews",
    "Arnold",
    "Wagner",
    "Willis",
    "Ray",
    "Watkins",
    "Olson",
    "Carroll",
    "Duncan",
    "Snyder",
    "Hart",
    "Cunningham",
    "Bradley",
    "Lane",
    "Andrews",
    "Ruiz",
    "Harper",
    "Fox",
    "Riley",
    "Armstrong",
    "Carpenter",
    "Weaver",
    "Greene",
    "Lawrence",
    "Elliott",
    "Chavez",
    "Sims",
    "Austin",
    "Peters",
    "Kelley",
    "Franklin",
    "Lawson",
    "Fields",
    "Gutierrez",
    "Ryan",
    "Schneider",
    "Wheeler",
    "Chapman",
    "Oliver",
    "Montgomery",
    "Richards",
    "Williamson",
    "Johnston",
    "Banks",
    "Meyer",
    "Bishop",
    "McCoy",
    "Howell",
    "Alvarez",
    "Morrison",
    "Hansen",
    "Fernandez",
    "Garza",
    "Harvey",
    "Little",
    "Burton",
    "Stanley",
    "Nguyen",
    "George",
    "Jacobs",
    "Reid",
    "Kim",
    "Fuller",
    "Lynch",
    "Dean",
    "Gilbert",
    "Garrett",
    "Romero",
    "Welch",
    "Larson",
    "Frazier",
    "Burke",
    "Hanson",
    "Day",
    "Mendoza",
  ],
  jobs: {
    demographics: {
      name: "👥 Demographics",
      color: "#1abc9c",
      jobs: [
        { name: "Child", icon: "👶", threshold: 1, ratio: 0.28 },
        { name: "Retiree", icon: "👴", threshold: 1, ratio: 0.08 },
        { name: "Housewife", icon: "🏠", threshold: 1, ratio: 0.2 },
        { name: "Student", icon: "📖", threshold: 20, ratio: 0.03 },
        { name: "Unemployed", icon: "😔", threshold: 50, ratio: 0.02 },
      ],
    },
    industry: {
      name: "🏭 Industry",
      color: "#95a5a6",
      jobs: [
        { name: "Factory Worker", icon: "🏭", threshold: 1, ratio: 0.08 },
        { name: "Skilled Worker", icon: "🔩", threshold: 20, ratio: 0.02 },
        { name: "Miner", icon: "⛏️", threshold: 50, ratio: 0.012 },
        { name: "Auto Mechanic", icon: "🔧", threshold: 30, ratio: 0.01 },
        { name: "Electrician", icon: "⚡", threshold: 50, ratio: 0.006 },
        { name: "Railwayman", icon: "🚂", threshold: 40, ratio: 0.008 },
        { name: "Radio Technician", icon: "📻", threshold: 150, ratio: 0.003 },
        { name: "Printer", icon: "🗞️", threshold: 80, ratio: 0.004 },
        { name: "Foreman", icon: "👷", threshold: 200, ratio: 0.002 },
        { name: "Engineer", icon: "📐", threshold: 500, ratio: 0.0015 },
        { name: "Aviator", icon: "✈️", threshold: 2000, ratio: 0.0003 },
        { name: "House Painter", icon: "🖌️", threshold: 30, ratio: 0.007 },
        { name: "Chimney Sweep", icon: "🏚️", threshold: 40, ratio: 0.004 },
      ],
    },
    commerce: {
      name: "🏪 Commerce",
      color: "#f39c12",
      jobs: [
        { name: "Salesperson", icon: "🛒", threshold: 10, ratio: 0.015 },
        { name: "Grocer", icon: "🥫", threshold: 20, ratio: 0.005 },
        { name: "Butcher", icon: "🥩", threshold: 40, ratio: 0.003 },
        { name: "Baker", icon: "🍞", threshold: 35, ratio: 0.004 },
        { name: "Pharmacist", icon: "💊", threshold: 150, ratio: 0.0015 },
        { name: "Hairdresser", icon: "💈", threshold: 60, ratio: 0.003 },
        { name: "Antique Dealer", icon: "📦", threshold: 300, ratio: 0.0008 },
        { name: "Jeweler", icon: "💎", threshold: 300, ratio: 0.0008 },
        { name: "Cobbler", icon: "👟", threshold: 40, ratio: 0.004 },
        { name: "Florist", icon: "💐", threshold: 80, ratio: 0.003 },
        { name: "Ice Cream Vendor", icon: "🍦", threshold: 80, ratio: 0.002 },
        { name: "Milkman", icon: "🥛", threshold: 50, ratio: 0.003 },
      ],
    },
    service: {
      name: "🍽️ Services",
      color: "#e74c3c",
      jobs: [
        { name: "Domestic Servant", icon: "🧹", threshold: 5, ratio: 0.02 },
        { name: "Waiter", icon: "🍽️", threshold: 25, ratio: 0.01 },
        { name: "Cook", icon: "👨‍🍳", threshold: 30, ratio: 0.006 },
        { name: "Bartender", icon: "🍸", threshold: 40, ratio: 0.004 },
        { name: "Driver", icon: "🚗", threshold: 60, ratio: 0.005 },
        { name: "Taxi Driver", icon: "🚕", threshold: 80, ratio: 0.004 },
        { name: "Bus Driver", icon: "🚌", threshold: 100, ratio: 0.003 },
        { name: "Sailor", icon: "⚓", threshold: 60, ratio: 0.004 },
        { name: "Captain", icon: "🚢", threshold: 500, ratio: 0.0008 },
        { name: "Hotel Keeper", icon: "🏨", threshold: 300, ratio: 0.001 },
        { name: "Housekeeper", icon: "🔑", threshold: 80, ratio: 0.003 },
        { name: "Nanny", icon: "👶", threshold: 60, ratio: 0.004 },
        { name: "Laundryman", icon: "👕", threshold: 40, ratio: 0.005 },
        {
          name: "Newspaper Deliverer",
          icon: "📰",
          threshold: 50,
          ratio: 0.004,
        },
        { name: "Postman", icon: "📬", threshold: 50, ratio: 0.004 },
        { name: "Landscaper", icon: "🌿", threshold: 80, ratio: 0.003 },
      ],
    },
    construction: {
      name: "🏗️ Construction",
      color: "#e67e22",
      jobs: [
        {
          name: "Construction Worker",
          icon: "🧱",
          threshold: 15,
          ratio: 0.015,
        },
        { name: "Carpenter", icon: "🪚", threshold: 30, ratio: 0.006 },
        { name: "Mason", icon: "🏠", threshold: 35, ratio: 0.005 },
        { name: "Plumber", icon: "🔧", threshold: 60, ratio: 0.004 },
        { name: "Architect", icon: "📏", threshold: 500, ratio: 0.0008 },
      ],
    },
    agriculture: {
      name: "🌾 Agriculture",
      color: "#27ae60",
      jobs: [
        { name: "Farmer", icon: "🌾", threshold: 1, ratio: 0.035 },
        { name: "Farm Worker", icon: "🚜", threshold: 10, ratio: 0.02 },
        { name: "Livestock Farmer", icon: "🐄", threshold: 30, ratio: 0.006 },
        { name: "Fisherman", icon: "🎣", threshold: 60, ratio: 0.002 },
      ],
    },
    law: {
      name: "⚖️ Order & Justice",
      color: "#3498db",
      jobs: [
        { name: "Police Officer", icon: "👮", threshold: 30, ratio: 0.006 },
        { name: "Military", icon: "🪖", threshold: 20, ratio: 0.008 },
        { name: "Private Detective", icon: "🔍", threshold: 200, ratio: 0.001 },
        { name: "BOI Agent", icon: "🕵️", threshold: 5000, ratio: 0.00008 },
        { name: "Firefighter", icon: "🚒", threshold: 80, ratio: 0.003 },
        { name: "Paramedic", icon: "🚑", threshold: 150, ratio: 0.002 },
        {
          name: "Forensic Photographer",
          icon: "📸",
          threshold: 1000,
          ratio: 0.0003,
        },
        { name: "Tax Inspector", icon: "🧾", threshold: 500, ratio: 0.0006 },
        { name: "Lawyer", icon: "⚖️", threshold: 200, ratio: 0.0015 },
        { name: "Judge", icon: "👨‍⚖️", threshold: 2000, ratio: 0.0002 },
      ],
    },
    medicine: {
      name: "🏥 Medicine",
      color: "#1abc9c",
      jobs: [
        { name: "Nurse", icon: "👩‍⚕️", threshold: 60, ratio: 0.004 },
        { name: "Doctor", icon: "⚕️", threshold: 300, ratio: 0.001 },
        { name: "Country Doctor", icon: "👨‍⚕️", threshold: 100, ratio: 0.002 },
        { name: "Surgeon", icon: "🩺", threshold: 1000, ratio: 0.0004 },
        { name: "Dentist", icon: "🦷", threshold: 500, ratio: 0.0006 },
        { name: "Forensic Doctor", icon: "⚰️", threshold: 2000, ratio: 0.0002 },
        { name: "Psychologist", icon: "🧠", threshold: 1000, ratio: 0.0004 },
      ],
    },
    professions: {
      name: "🎓 Liberal Professions",
      color: "#9b59b6",
      jobs: [
        { name: "Teacher", icon: "📚", threshold: 40, ratio: 0.005 },
        { name: "Secretary", icon: "📝", threshold: 80, ratio: 0.006 },
        { name: "Accountant", icon: "🧮", threshold: 150, ratio: 0.002 },
        { name: "Translator", icon: "📜", threshold: 500, ratio: 0.0006 },
        { name: "Occultist", icon: "🔮", threshold: 5000, ratio: 0.00008 },
        { name: "Spiritualist", icon: "🎩", threshold: 3000, ratio: 0.0001 },
        { name: "Fortune Teller", icon: "🔮", threshold: 200, ratio: 0.0012 },
      ],
    },
    university: {
      name: "🔬 University & Research",
      color: "#8e44ad",
      jobs: [
        { name: "Professor", icon: "🎓", threshold: 1000, ratio: 0.0004 },
        {
          name: "Biology Researcher",
          icon: "🔬",
          threshold: 2000,
          ratio: 0.0002,
        },
        { name: "Chemist", icon: "⚗️", threshold: 2000, ratio: 0.0002 },
        { name: "Lab Technician", icon: "🧪", threshold: 1000, ratio: 0.0003 },
        {
          name: "Academic Archaeologist",
          icon: "🏺",
          threshold: 5000,
          ratio: 0.00008,
        },
        { name: "Anthropologist", icon: "🌍", threshold: 5000, ratio: 0.00008 },
        { name: "Librarian", icon: "📖", threshold: 500, ratio: 0.0006 },
        { name: "Historian", icon: "🏛️", threshold: 2000, ratio: 0.0002 },
        { name: "Linguist", icon: "📜", threshold: 5000, ratio: 0.00006 },
        { name: "Mathematician", icon: "📐", threshold: 3000, ratio: 0.0001 },
        { name: "Geographer", icon: "🧭", threshold: 3000, ratio: 0.0001 },
        { name: "Archaeologist", icon: "🏺", threshold: 10000, ratio: 0.00006 },
      ],
    },
    media: {
      name: "📰 Media & Arts",
      color: "#e91e63",
      jobs: [
        { name: "Journalist", icon: "📰", threshold: 100, ratio: 0.002 },
        { name: "Photographer", icon: "📷", threshold: 150, ratio: 0.0015 },
        { name: "Musician", icon: "🎵", threshold: 100, ratio: 0.0015 },
        { name: "Actor", icon: "🎭", threshold: 500, ratio: 0.0006 },
        { name: "Writer", icon: "✍️", threshold: 1000, ratio: 0.0004 },
        { name: "Painter", icon: "🎨", threshold: 200, ratio: 0.001 },
      ],
    },
    elite: {
      name: "🎩 Elite",
      color: "#8e44ad",
      jobs: [
        { name: "Businessman", icon: "💼", threshold: 150, ratio: 0.003 },
        { name: "Banker", icon: "🏦", threshold: 500, ratio: 0.0008 },
        { name: "Politician", icon: "🏛️", threshold: 500, ratio: 0.0008 },
        { name: "Industrialist", icon: "🏭", threshold: 5000, ratio: 0.00015 },
        { name: "Wealthy Heir", icon: "💰", threshold: 1000, ratio: 0.0004 },
      ],
    },
    underworld: {
      name: "🌙 Underworld",
      color: "#2c3e50",
      jobs: [
        { name: "Bootlegger", icon: "🥃", threshold: 50, ratio: 0.004 },
        { name: "Bookmaker", icon: "🎲", threshold: 80, ratio: 0.002 },
        { name: "Henchman", icon: "👊", threshold: 60, ratio: 0.003 },
        { name: "Prostitute", icon: "💋", threshold: 50, ratio: 0.005 },
        { name: "Smuggler", icon: "📦", threshold: 150, ratio: 0.0015 },
        { name: "Hitman", icon: "🔫", threshold: 2000, ratio: 0.00015 },
        { name: "Capo", icon: "🎩", threshold: 1000, ratio: 0.0004 },
        { name: "Crime Boss", icon: "👔", threshold: 50000, ratio: 0.00004 },
      ],
    },
  },
};

export const JOB_FEMALE_RATIO: Record<string, number> = {
  Prostitute: 0.97,
  Housewife: 1.0,
  Housekeeper: 0.9,
  Nanny: 0.9,
  Nurse: 0.85,
  Secretary: 0.8,
  Teacher: 0.65,
  Laundryman: 0.7,
  Florist: 0.65,
  "Fortune Teller": 0.6,
  "Domestic Servant": 0.6,
  Librarian: 0.55,
  Translator: 0.5,
  Salesperson: 0.4,
  Hairdresser: 0.45,
  Accountant: 0.35,
  Actor: 0.4,
  Musician: 0.35,
  Psychologist: 0.4,
  Painter: 0.3,
  Photographer: 0.3,
  Journalist: 0.28,
  Writer: 0.35,
  Spiritualist: 0.55,
  Pharmacist: 0.25,
  Dentist: 0.2,
  Baker: 0.3,
  "Ice Cream Vendor": 0.3,
  Grocer: 0.25,
  Waiter: 0.35,
  Cook: 0.25,
  Bookmaker: 0.1,
  Student: 0.35,
  Unemployed: 0.2,
  Farmer: 0.12,
  "Farm Worker": 0.1,
  "Livestock Farmer": 0.08,
  Fisherman: 0.05,
  "Factory Worker": 0.08,
  "Skilled Worker": 0.05,
  Miner: 0.02,
  "Auto Mechanic": 0.03,
  Electrician: 0.03,
  Railwayman: 0.04,
  "Radio Technician": 0.06,
  Printer: 0.08,
  Foreman: 0.04,
  Engineer: 0.05,
  Aviator: 0.04,
  "House Painter": 0.04,
  "Chimney Sweep": 0.02,
  "Construction Worker": 0.04,
  Carpenter: 0.03,
  Mason: 0.03,
  Plumber: 0.03,
  Architect: 0.08,
  "Police Officer": 0.05,
  Military: 0.03,
  "Private Detective": 0.12,
  "BOI Agent": 0.05,
  Firefighter: 0.03,
  Paramedic: 0.2,
  "Forensic Photographer": 0.1,
  "Tax Inspector": 0.1,
  Lawyer: 0.08,
  Judge: 0.04,
  Doctor: 0.1,
  "Country Doctor": 0.08,
  Surgeon: 0.05,
  "Forensic Doctor": 0.06,
  Bartender: 0.1,
  Driver: 0.05,
  "Taxi Driver": 0.04,
  "Bus Driver": 0.04,
  Sailor: 0.04,
  Captain: 0.03,
  "Hotel Keeper": 0.2,
  Landscaper: 0.08,
  "Newspaper Deliverer": 0.15,
  Postman: 0.1,
  Butcher: 0.06,
  Jeweler: 0.15,
  "Antique Dealer": 0.2,
  Cobbler: 0.05,
  Milkman: 0.08,
  Bootlegger: 0.05,
  Henchman: 0.03,
  Smuggler: 0.06,
  Hitman: 0.05,
  Capo: 0.03,
  "Crime Boss": 0.02,
  Businessman: 0.08,
  Banker: 0.06,
  Politician: 0.05,
  Industrialist: 0.04,
  "Wealthy Heir": 0.45,
  Professor: 0.2,
  "Biology Researcher": 0.18,
  Chemist: 0.12,
  "Lab Technician": 0.25,
  "Academic Archaeologist": 0.15,
  Anthropologist: 0.18,
  Historian: 0.15,
  Linguist: 0.3,
  Mathematician: 0.08,
  Geographer: 0.1,
  Archaeologist: 0.15,
  Occultist: 0.3,
};

export const skillsBase: Record<string, number> = {
  Anthropology: 1,
  Archaeology: 1,
  "Art/Craft (Fine Arts)": 5,
  "Art/Craft (Photography)": 5,
  "Art/Craft (Cooking)": 5,
  "Art/Craft (Carpentry)": 5,
  "Art/Craft (Plumbing)": 5,
  "Art/Craft (Mechanics)": 5,
  "Art/Craft (Blacksmith)": 5,
  "Art/Craft (Barber)": 5,
  "Art/Craft (Tailor)": 5,
  "Art/Craft (Acting)": 5,
  "Art/Craft (Forgery)": 5,
  "Art/Craft (Singing)": 5,
  "Fast Talk": 5,
  "Library Use": 20,
  Charm: 15,
  "Firearms (Handgun)": 20,
  "Firearms (Rifle)": 25,
  "Firearms (Submachine Gun)": 15,
  "Fighting (Brawl)": 25,
  "Fighting (Axe)": 10,
  Accounting: 5,
  "Drive Auto": 20,
  "Drive (Heavy Vehicle)": 1,
  "Credit Rating": 0,
  Locksmith: 1,
  Stealth: 20,
  "Animal Handling": 5,
  Law: 5,
  Listen: 20,
  "Electrical Repair": 10,
  Ride: 5,
  Dodge: 0,
  Appraise: 5,
  Demolitions: 1,
  Climb: 20,
  History: 5,
  Hypnosis: 1,
  Disguise: 5,
  Intimidate: 15,
  Throw: 20,
  "Own Language": 0,
  "Language (French)": 1,
  "Language (German)": 1,
  "Language (Spanish)": 1,
  "Language (Italian)": 1,
  "Language (Latin)": 1,
  "Language (Greek)": 1,
  "Lip Reading": 1,
  "Mechanical Repair": 10,
  Medicine: 1,
  "Cthulhu Mythos": 0,
  Swim: 20,
  "Natural World": 10,
  Occult: 5,
  Navigate: 10,
  Persuade: 10,
  Pickpocket: 10,
  "Pilot (Aircraft)": 1,
  "Pilot (Boat)": 1,
  Track: 10,
  Diving: 1,
  "First Aid": 30,
  Psychoanalysis: 1,
  Psychology: 10,
  Jump: 20,
  "Science (Astronomy)": 1,
  "Science (Biology)": 1,
  "Science (Botany)": 1,
  "Science (Chemistry)": 1,
  "Science (Forensics)": 1,
  "Science (Cryptography)": 1,
  "Science (Geology)": 1,
  "Science (Engineering)": 1,
  "Science (Mathematics)": 1,
  "Science (Meteorology)": 1,
  "Science (Pharmacology)": 1,
  "Science (Physics)": 1,
  "Science (Zoology)": 1,
  Survival: 10,
  "Spot Hidden": 25,
};

export const weaponsList = [
  { name: "Fist", damage: "1D3+DB" },
  { name: "Kick", damage: "1D4+DB" },
  { name: "Knife", damage: "1D4+DB" },
  { name: "Butcher Knife", damage: "1D6+DB" },
  { name: "Razor", damage: "1D3" },
  { name: "Baton", damage: "1D6+DB" },
  { name: "Brass Knuckles", damage: "1D3+1+DB" },
  { name: "Axe", damage: "1D8+1+DB" },
  { name: "Pickaxe", damage: "1D8+1+DB" },
  { name: "Shovel", damage: "1D6+DB" },
  { name: ".22 Revolver", damage: "1D6" },
  { name: ".32 Revolver", damage: "1D8" },
  { name: ".38 Revolver", damage: "1D10" },
  { name: ".45 Revolver", damage: "1D10+2" },
  { name: ".32 Automatic", damage: "1D8" },
  { name: ".45 Automatic", damage: "1D10+2" },
  { name: "Shotgun", damage: "4D6/2D6/1D6" },
  { name: "Rifle", damage: "2D6" },
  { name: ".41 Derringer", damage: "1D8" },
  { name: "Thompson", damage: "1D10+2" },
];

// Mapping French skill names (from original Google Sites data) to their English equivalents.
// This is used by logic.generateCthulhuStats to ensure all generated stats use
// the English notation required by Foundry VTT. The list is derived from the
// work/embedded_script_with_newlines.js translation table and kept in sync
// with it.
export const skillTranslations: Record<string, string> = {
  Anthropologie: "Anthropology",
  Archéologie: "Archaeology",
  "Arts et métiers (Beaux-arts)": "Art/Craft (Fine Arts)",
  "Arts et métiers (Photographie)": "Art/Craft (Photography)",
  "Arts et métiers (Cuisine)": "Art/Craft (Cooking)",
  "Arts et métiers (Menuiserie)": "Art/Craft (Carpentry)",
  "Arts et métiers (Plomberie)": "Art/Craft (Plumbing)",
  "Arts et métiers (Mécanique)": "Art/Craft (Mechanics)",
  "Arts et métiers (Forgeron)": "Art/Craft (Blacksmith)",
  "Arts et métiers (Barbier)": "Art/Craft (Barber)",
  "Arts et métiers (Tailleur)": "Art/Craft (Tailor)",
  "Arts et métiers (Comédie)": "Art/Craft (Acting)",
  "Arts et métiers (Contrefaçon)": "Art/Craft (Forgery)",
  "Arts et métiers (Chant)": "Art/Craft (Singing)",
  Baratin: "Fast Talk",
  Bibliothèque: "Library Use",
  Charme: "Charm",
  "Combat. Arme à feu (Armes de poing)": "Firearms (Handgun)",
  "Combat. Arme à feu (Fusils)": "Firearms (Rifle)",
  "Combat. Arme à feu (Mitraillettes)": "Firearms (Submachine Gun)",
  "Combat. Au Contact (Corps à corps)": "Fighting (Brawl)",
  "Combat. Au Contact (Haches)": "Fighting (Axe)",
  Comptabilité: "Accounting",
  Conduite: "Drive Auto",
  "Conduite (Engin lourd)": "Drive (Heavy Vehicle)",
  Crédit: "Credit Rating",
  Crochetage: "Locksmith",
  Discrétion: "Stealth",
  Dressage: "Animal Handling",
  Droit: "Law",
  Ecouter: "Listen",
  Electricité: "Electrical Repair",
  Equitation: "Ride",
  Esquive: "Dodge",
  Estimation: "Appraise",
  Explosifs: "Demolitions",
  Grimper: "Climb",
  Histoire: "History",
  Hypnose: "Hypnosis",
  Imposture: "Disguise",
  Intimidation: "Intimidate",
  Lancer: "Throw",
  "Langue maternelle": "Own Language",
  "Langues (Français)": "Language (French)",
  "Langues (Allemand)": "Language (German)",
  "Langues (Espagnol)": "Language (Spanish)",
  "Langues (Italien)": "Language (Italian)",
  "Langues (Latin)": "Language (Latin)",
  "Langues (Grec)": "Language (Greek)",
  "Lecture sur les lèvres": "Lip Reading",
  Mécanique: "Mechanical Repair",
  Médecine: "Medicine",
  "Mythe de Cthulhu": "Cthulhu Mythos",
  Nager: "Swim",
  Naturalisme: "Natural World",
  Occultisme: "Occult",
  Orientation: "Navigate",
  Persuasion: "Persuade",
  Pickpocket: "Pickpocket",
  "Pilotage (Avion)": "Pilot (Aircraft)",
  "Pilotage (Bateaux)": "Pilot (Boat)",
  Pister: "Track",
  Plongée: "Diving",
  "Premiers soins": "First Aid",
  Psychanalyse: "Psychoanalysis",
  Psychologie: "Psychology",
  Sauter: "Jump",
  "Sciences (Astronomie)": "Science (Astronomy)",
  "Sciences (Biologie)": "Science (Biology)",
  "Sciences (Botanique)": "Science (Botany)",
  "Sciences (Chimie)": "Science (Chemistry)",
  "Sciences (Criminalistique)": "Science (Forensics)",
  "Sciences (Cryptographie)": "Science (Cryptography)",
  "Sciences (Géologie)": "Science (Geology)",
  "Sciences (Ingénierie)": "Science (Engineering)",
  "Sciences (Mathématiques)": "Science (Mathematics)",
  "Sciences (Météorologie)": "Science (Meteorology)",
  "Sciences (Pharmacologie)": "Science (Pharmacology)",
  "Sciences (Physique)": "Science (Physics)",
  "Sciences (Zoologie)": "Science (Zoology)",
  Survie: "Survival",
  "Trouver Objet Caché": "Spot Hidden",
};

export const jobSkillProfiles: Record<string, any> = {
  _default: {
    skills: {
      "Own Language": [40, 60],
      Listen: [25, 45],
      "Spot Hidden": [25, 45],
      Dodge: [15, 30],
      Psychology: [15, 35],
      "First Aid": [30, 45],
    },
    credit: [5, 20],
    weapons: ["Fist"],
    statBonus: {},
  },
  "Factory Worker": {
    skills: {
      "Mechanical Repair": [40, 60],
      "Electrical Repair": [25, 45],
      Climb: [30, 50],
      "Drive Auto": [25, 45],
      "First Aid": [30, 45],
      Listen: [30, 50],
      "Combat. Au Contact (Corps à corps)": [30, 50],
      Dodge: [25, 40],
      Jump: [25, 40],
      Throw: [25, 45],
      "Spot Hidden": [25, 40],
    },
    credit: [9, 20],
    weapons: ["Fist", "Baton"],
    statBonus: { FOR: 10, CON: 10 },
  },
  "Skilled Worker": {
    skills: {
      "Mechanical Repair": [50, 70],
      "Electrical Repair": [40, 60],
      "Arts et métiers (Mécanique)": [45, 65],
      "Drive Auto": [30, 50],
      "Sciences (Ingénierie)": [20, 40],
      Accounting: [15, 30],
      Listen: [30, 45],
      Climb: [30, 45],
      "First Aid": [35, 50],
      Appraise: [25, 45],
      "Spot Hidden": [25, 40],
    },
    credit: [15, 30],
    weapons: ["Fist"],
    statBonus: { FOR: 5, DEX: 10, INT: 5 },
  },
  Miner: {
    skills: {
      Climb: [45, 65],
      Navigate: [40, 60],
      "Mechanical Repair": [30, 50],
      Survival: [35, 55],
      "First Aid": [35, 50],
      Listen: [35, 55],
      "Spot Hidden": [30, 50],
      "Sciences (Géologie)": [20, 40],
      "Combat. Au Contact (Haches)": [30, 50],
      Dodge: [25, 40],
      Swim: [20, 35],
      Throw: [25, 45],
    },
    credit: [9, 20],
    weapons: ["Fist", "Pickaxe"],
    statBonus: { FOR: 15, CON: 15 },
  },
  "Auto Mechanic": {
    skills: {
      "Mechanical Repair": [60, 80],
      "Electrical Repair": [40, 60],
      "Drive Auto": [50, 70],
      "Arts et métiers (Mécanique)": [45, 65],
      "Fast Talk": [25, 45],
      Appraise: [30, 50],
      Listen: [25, 40],
      Accounting: [20, 35],
      "Sciences (Ingénierie)": [15, 30],
      "Spot Hidden": [25, 40],
      "First Aid": [30, 45],
    },
    credit: [15, 35],
    weapons: ["Fist"],
    statBonus: { DEX: 10, INT: 5 },
  },
  Electrician: {
    skills: {
      "Electrical Repair": [60, 80],
      "Mechanical Repair": [40, 60],
      Climb: [35, 55],
      "Sciences (Physique)": [25, 45],
      "Sciences (Ingénierie)": [20, 40],
      "First Aid": [35, 50],
      Appraise: [25, 45],
      "Drive Auto": [25, 40],
      Listen: [25, 40],
      "Spot Hidden": [25, 40],
      "Sciences (Mathématiques)": [15, 30],
    },
    credit: [15, 35],
    weapons: ["Fist"],
    statBonus: { INT: 10, DEX: 10 },
  },
  Railwayman: {
    skills: {
      "Conduite (Engin lourd)": [50, 70],
      "Mechanical Repair": [45, 65],
      Navigate: [40, 60],
      Listen: [35, 55],
      "Spot Hidden": [30, 50],
      "First Aid": [35, 50],
      "Electrical Repair": [25, 45],
      Survival: [25, 40],
      "Combat. Au Contact (Corps à corps)": [25, 40],
      Dodge: [25, 40],
      Climb: [25, 45],
    },
    credit: [15, 30],
    weapons: ["Fist", "Baton"],
    statBonus: { CON: 10, INT: 5 },
  },
  "Radio Technician": {
    skills: {
      "Electrical Repair": [60, 80],
      "Sciences (Physique)": [50, 70],
      "Mechanical Repair": [40, 60],
      "Sciences (Mathématiques)": [35, 55],
      Navigate: [40, 60],
      Listen: [45, 65],
      "Sciences (Ingénierie)": [30, 50],
      "Spot Hidden": [30, 50],
      Accounting: [25, 45],
    },
    credit: [20, 40],
    weapons: ["Fist"],
    statBonus: { INT: 10, DEX: 10 },
  },
  Printer: {
    skills: {
      "Arts et métiers (Contrefaçon)": [50, 70],
      "Mechanical Repair": [45, 65],
      "Own Language": [55, 75],
      Accounting: [35, 55],
      "Library Use": [35, 55],
      Listen: [30, 50],
      "Spot Hidden": [30, 50],
      Appraise: [30, 50],
      "Fast Talk": [25, 45],
      History: [25, 45],
    },
    credit: [15, 35],
    weapons: ["Fist"],
    statBonus: { INT: 5, DEX: 10 },
  },
  Foreman: {
    skills: {
      Intimidate: [50, 70],
      Accounting: [40, 60],
      "Mechanical Repair": [35, 55],
      Psychology: [40, 60],
      Persuade: [35, 55],
      Listen: [35, 55],
      "Fast Talk": [30, 50],
      Law: [25, 40],
      "First Aid": [30, 45],
      "Combat. Au Contact (Corps à corps)": [30, 45],
      "Own Language": [50, 70],
    },
    credit: [25, 45],
    weapons: ["Fist", "Baton"],
    statBonus: { POU: 10, INT: 5 },
  },
  Engineer: {
    skills: {
      "Sciences (Ingénierie)": [60, 80],
      "Sciences (Physique)": [45, 65],
      "Sciences (Mathématiques)": [50, 70],
      "Mechanical Repair": [45, 65],
      "Electrical Repair": [40, 60],
      "Library Use": [45, 65],
      Accounting: [35, 55],
      Persuade: [30, 50],
      Appraise: [40, 60],
      "Drive Auto": [30, 45],
      "Own Language": [55, 75],
    },
    credit: [35, 55],
    weapons: ["Fist"],
    statBonus: { INT: 15, EDU: 15 },
  },
  Aviator: {
    skills: {
      "Pilotage (Avion)": [65, 85],
      "Mechanical Repair": [50, 70],
      Navigate: [55, 75],
      "Sciences (Météorologie)": [45, 65],
      "Sciences (Physique)": [35, 55],
      "Drive Auto": [40, 60],
      Listen: [35, 55],
      "Combat. Arme à feu (Armes de poing)": [35, 55],
      Survival: [30, 50],
      "Spot Hidden": [30, 50],
    },
    credit: [30, 55],
    weapons: [".38 Revolver"],
    statBonus: { DEX: 15, INT: 10 },
  },
  "House Painter": {
    skills: {
      Climb: [50, 70],
      Appraise: [35, 55],
      "Mechanical Repair": [30, 50],
      Listen: [30, 45],
      "Spot Hidden": [30, 50],
      "First Aid": [30, 45],
      "Fast Talk": [25, 45],
      Jump: [30, 50],
      "Drive Auto": [25, 40],
      Dodge: [25, 40],
    },
    credit: [9, 25],
    weapons: ["Fist"],
    statBonus: { DEX: 5, FOR: 5 },
  },
  "Chimney Sweep": {
    skills: {
      Climb: [60, 80],
      Stealth: [50, 70],
      Navigate: [35, 55],
      "Spot Hidden": [40, 60],
      Listen: [35, 55],
      Jump: [35, 55],
      "First Aid": [30, 45],
      "Mechanical Repair": [25, 45],
      Dodge: [30, 50],
      Survival: [30, 50],
    },
    credit: [9, 20],
    weapons: ["Fist"],
    statBonus: { DEX: 15, CON: 5 },
  },
  Salesperson: {
    skills: {
      "Fast Talk": [50, 70],
      Charm: [45, 65],
      Persuade: [45, 65],
      Psychology: [40, 60],
      Accounting: [35, 55],
      Appraise: [40, 60],
      Listen: [35, 55],
      Disguise: [25, 45],
      "Own Language": [55, 75],
      "Spot Hidden": [25, 40],
    },
    credit: [15, 40],
    weapons: ["Fist"],
    statBonus: { APP: 10, POU: 5 },
  },
  Grocer: {
    skills: {
      Accounting: [45, 65],
      "Fast Talk": [35, 55],
      Psychology: [35, 55],
      Appraise: [40, 60],
      Listen: [35, 55],
      Charm: [30, 50],
      Persuade: [30, 50],
      "Own Language": [50, 70],
      "Spot Hidden": [30, 45],
      "First Aid": [30, 45],
    },
    credit: [20, 45],
    weapons: ["Fist"],
    statBonus: {},
  },
  Butcher: {
    skills: {
      "Arts et métiers (Cuisine)": [55, 75],
      Accounting: [35, 55],
      "Fast Talk": [30, 50],
      Intimidate: [35, 55],
      "Combat. Au Contact (Corps à corps)": [35, 55],
      Appraise: [35, 55],
      Listen: [30, 45],
      Psychology: [25, 40],
      "First Aid": [30, 45],
      "Sciences (Biologie)": [20, 35],
      "Spot Hidden": [25, 40],
    },
    credit: [20, 40],
    weapons: ["Butcher Knife"],
    statBonus: { FOR: 10, CON: 5 },
  },
  Baker: {
    skills: {
      "Arts et métiers (Cuisine)": [60, 80],
      Accounting: [35, 55],
      "Fast Talk": [30, 50],
      Charm: [30, 50],
      Appraise: [35, 55],
      Listen: [30, 45],
      "Sciences (Chimie)": [20, 35],
      "Drive Auto": [20, 35],
      "Own Language": [45, 65],
      Psychology: [25, 40],
    },
    credit: [20, 40],
    weapons: ["Fist"],
    statBonus: { CON: 5 },
  },
  Pharmacist: {
    skills: {
      "Sciences (Pharmacologie)": [60, 80],
      "Sciences (Chimie)": [50, 70],
      Medicine: [40, 60],
      Accounting: [40, 60],
      "Library Use": [45, 65],
      Psychology: [35, 55],
      "First Aid": [45, 65],
      "Sciences (Biologie)": [30, 50],
      Persuade: [30, 50],
      "Own Language": [55, 75],
      "Langues (Latin)": [25, 45],
    },
    credit: [40, 60],
    weapons: ["Fist"],
    statBonus: { INT: 10, EDU: 15 },
  },
  Hairdresser: {
    skills: {
      "Arts et métiers (Barbier)": [60, 80],
      Charm: [45, 65],
      "Fast Talk": [45, 65],
      Psychology: [40, 60],
      Listen: [45, 65],
      Persuade: [30, 50],
      "Spot Hidden": [25, 40],
      Stealth: [25, 40],
      "First Aid": [30, 45],
      "Own Language": [50, 70],
    },
    credit: [15, 35],
    weapons: ["Razor"],
    statBonus: { APP: 5, DEX: 10 },
  },
  "Antique Dealer": {
    skills: {
      Appraise: [65, 85],
      History: [55, 75],
      "Library Use": [50, 70],
      "Fast Talk": [45, 65],
      Psychology: [40, 60],
      Charm: [35, 55],
      Persuade: [35, 55],
      "Spot Hidden": [45, 65],
      Occult: [25, 45],
      Archaeology: [25, 45],
      Locksmith: [20, 35],
    },
    credit: [40, 65],
    weapons: ["Fist"],
    statBonus: { INT: 10, EDU: 10 },
  },
  Jeweler: {
    skills: {
      "Arts et métiers (Beaux-arts)": [60, 80],
      Appraise: [60, 80],
      History: [35, 55],
      Accounting: [40, 60],
      Charm: [35, 55],
      Persuade: [35, 55],
      "Spot Hidden": [40, 60],
      "Library Use": [30, 50],
      Locksmith: [30, 50],
      "Sciences (Chimie)": [20, 35],
      Psychology: [30, 50],
    },
    credit: [45, 70],
    weapons: ["Fist"],
    statBonus: { DEX: 10, INT: 5 },
  },
  Cobbler: {
    skills: {
      "Arts et métiers (Tailleur)": [60, 80],
      Appraise: [40, 60],
      "Fast Talk": [30, 50],
      Listen: [35, 55],
      "Spot Hidden": [35, 55],
      Accounting: [30, 50],
      Psychology: [25, 45],
      "Mechanical Repair": [25, 45],
      "First Aid": [25, 40],
      "Own Language": [45, 65],
    },
    credit: [15, 35],
    weapons: ["Fist"],
    statBonus: { DEX: 10 },
  },
  Florist: {
    skills: {
      "Natural World": [55, 75],
      "Sciences (Botanique)": [50, 70],
      Charm: [45, 65],
      "Fast Talk": [40, 60],
      Appraise: [35, 55],
      Listen: [40, 60],
      Accounting: [35, 55],
      Psychology: [35, 55],
      Persuade: [35, 55],
      "Own Language": [50, 70],
    },
    credit: [15, 35],
    weapons: ["Fist"],
    statBonus: { APP: 5 },
  },
  "Ice Cream Vendor": {
    skills: {
      "Arts et métiers (Cuisine)": [55, 75],
      "Fast Talk": [40, 60],
      Charm: [40, 60],
      Appraise: [35, 55],
      Accounting: [35, 55],
      Listen: [35, 55],
      "Sciences (Chimie)": [20, 35],
      Psychology: [25, 40],
      "First Aid": [25, 40],
      "Drive Auto": [20, 35],
    },
    credit: [15, 35],
    weapons: ["Fist"],
    statBonus: {},
  },
  Milkman: {
    skills: {
      "Drive Auto": [50, 70],
      "Animal Handling": [45, 65],
      Navigate: [40, 60],
      Listen: [35, 55],
      "Fast Talk": [35, 55],
      Appraise: [35, 55],
      "First Aid": [30, 45],
      Accounting: [30, 50],
      "Spot Hidden": [25, 40],
    },
    credit: [9, 25],
    weapons: ["Fist"],
    statBonus: { CON: 5 },
  },
  "Domestic Servant": {
    skills: {
      Stealth: [50, 70],
      Listen: [50, 70],
      Psychology: [40, 60],
      "Spot Hidden": [40, 60],
      "First Aid": [35, 55],
      "Arts et métiers (Cuisine)": [35, 55],
      Charm: [25, 45],
      "Fast Talk": [25, 45],
      Dodge: [25, 40],
      "Own Language": [45, 65],
    },
    credit: [5, 15],
    weapons: ["Fist"],
    statBonus: { DEX: 5 },
  },
  Waiter: {
    skills: {
      Charm: [45, 65],
      Listen: [45, 65],
      Psychology: [40, 60],
      "Fast Talk": [35, 55],
      Stealth: [35, 55],
      Dodge: [35, 55],
      Accounting: [25, 45],
      "Spot Hidden": [30, 45],
      "Own Language": [45, 65],
      "First Aid": [25, 40],
    },
    credit: [9, 25],
    weapons: ["Fist"],
    statBonus: { DEX: 10, APP: 5 },
  },
  Cook: {
    skills: {
      "Arts et métiers (Cuisine)": [60, 80],
      Appraise: [40, 60],
      Listen: [35, 55],
      "Fast Talk": [30, 50],
      Accounting: [30, 50],
      "Sciences (Chimie)": [20, 35],
      "First Aid": [30, 45],
      Intimidate: [25, 45],
      Psychology: [25, 40],
      "Spot Hidden": [25, 40],
    },
    credit: [15, 35],
    weapons: ["Butcher Knife"],
    statBonus: { CON: 5, DEX: 5 },
  },
  Bartender: {
    skills: {
      Charm: [45, 65],
      "Fast Talk": [50, 70],
      Psychology: [50, 70],
      Listen: [55, 75],
      Intimidate: [35, 55],
      "Combat. Au Contact (Corps à corps)": [30, 50],
      Stealth: [30, 50],
      Appraise: [30, 50],
      "Spot Hidden": [30, 45],
      "Own Language": [50, 70],
    },
    credit: [15, 35],
    weapons: ["Fist", "Baton"],
    statBonus: { APP: 5, POU: 5 },
  },
  Driver: {
    skills: {
      "Drive Auto": [60, 80],
      "Mechanical Repair": [45, 65],
      Navigate: [45, 65],
      Listen: [40, 60],
      "Spot Hidden": [35, 55],
      Stealth: [35, 55],
      "Combat. Arme à feu (Armes de poing)": [30, 50],
      "First Aid": [30, 45],
      Dodge: [30, 45],
      Psychology: [25, 40],
    },
    credit: [20, 40],
    weapons: ["Fist", ".32 Revolver"],
    statBonus: { DEX: 10 },
  },
  "Taxi Driver": {
    skills: {
      "Drive Auto": [60, 80],
      Navigate: [55, 75],
      "Fast Talk": [40, 60],
      Listen: [45, 65],
      Psychology: [40, 60],
      "Mechanical Repair": [35, 55],
      Stealth: [30, 50],
      Charm: [30, 50],
      Dodge: [25, 40],
      "Spot Hidden": [30, 45],
    },
    credit: [9, 30],
    weapons: ["Fist"],
    statBonus: { DEX: 5 },
  },
  "Bus Driver": {
    skills: {
      "Conduite (Engin lourd)": [60, 80],
      Navigate: [50, 70],
      "Fast Talk": [35, 55],
      Listen: [40, 60],
      Psychology: [35, 55],
      "Mechanical Repair": [35, 55],
      "First Aid": [30, 45],
      Dodge: [25, 40],
      "Spot Hidden": [25, 40],
      Accounting: [25, 40],
    },
    credit: [15, 30],
    weapons: ["Fist"],
    statBonus: { CON: 5 },
  },
  Sailor: {
    skills: {
      Swim: [60, 80],
      "Pilotage (Bateaux)": [55, 75],
      Navigate: [50, 70],
      Survival: [45, 65],
      "Sciences (Météorologie)": [40, 60],
      "Mechanical Repair": [35, 55],
      Climb: [40, 60],
      "Combat. Au Contact (Corps à corps)": [35, 55],
      Listen: [35, 55],
      "Natural World": [30, 50],
      "First Aid": [30, 45],
    },
    credit: [10, 25],
    weapons: ["Knife", "Fist"],
    statBonus: { FOR: 5, CON: 10, DEX: 5 },
  },
  Captain: {
    skills: {
      "Pilotage (Bateaux)": [70, 90],
      Navigate: [60, 80],
      "Sciences (Météorologie)": [55, 75],
      Intimidate: [50, 70],
      Persuade: [45, 65],
      Psychology: [40, 60],
      Accounting: [40, 60],
      Law: [35, 55],
      Survival: [40, 60],
      "Combat. Arme à feu (Armes de poing)": [35, 55],
      "Own Language": [55, 75],
    },
    credit: [40, 65],
    weapons: [".38 Revolver"],
    statBonus: { POU: 10, INT: 10 },
  },
  "Hotel Keeper": {
    skills: {
      Accounting: [50, 70],
      Charm: [45, 65],
      Persuade: [45, 65],
      Psychology: [45, 65],
      "Fast Talk": [40, 60],
      Listen: [40, 60],
      Law: [30, 50],
      Appraise: [35, 55],
      Intimidate: [30, 50],
      "Own Language": [55, 75],
    },
    credit: [40, 60],
    weapons: ["Fist"],
    statBonus: { APP: 5, INT: 5 },
  },
  Housekeeper: {
    skills: {
      Stealth: [55, 75],
      Listen: [50, 70],
      Psychology: [50, 70],
      Accounting: [45, 65],
      "Arts et métiers (Cuisine)": [45, 65],
      "Spot Hidden": [45, 65],
      Persuade: [35, 55],
      "First Aid": [40, 60],
      "Own Language": [55, 75],
      Charm: [30, 50],
    },
    credit: [10, 25],
    weapons: ["Fist"],
    statBonus: { INT: 5, POU: 5 },
  },
  Nanny: {
    skills: {
      "First Aid": [50, 70],
      Psychology: [50, 70],
      Charm: [50, 70],
      Listen: [45, 65],
      Stealth: [40, 60],
      "Fast Talk": [35, 55],
      "Arts et métiers (Cuisine)": [35, 55],
      Persuade: [35, 55],
      "Spot Hidden": [35, 55],
      "Own Language": [50, 70],
    },
    credit: [5, 20],
    weapons: ["Fist"],
    statBonus: { POU: 5, APP: 5 },
  },
  Laundryman: {
    skills: {
      "Arts et métiers (Tailleur)": [55, 75],
      Appraise: [35, 55],
      Listen: [35, 55],
      "Fast Talk": [30, 50],
      Accounting: [30, 50],
      "First Aid": [30, 45],
      "Sciences (Chimie)": [20, 35],
      Psychology: [25, 40],
      "Spot Hidden": [30, 50],
      "Drive Auto": [20, 35],
    },
    credit: [9, 20],
    weapons: ["Fist"],
    statBonus: { FOR: 5, CON: 5 },
  },
  "Newspaper Deliverer": {
    skills: {
      Navigate: [55, 75],
      "Drive Auto": [50, 70],
      Listen: [40, 60],
      "Fast Talk": [35, 55],
      "Spot Hidden": [35, 55],
      Stealth: [35, 55],
      Psychology: [30, 50],
      Climb: [30, 50],
      Jump: [30, 50],
      "First Aid": [25, 40],
    },
    credit: [5, 15],
    weapons: ["Fist"],
    statBonus: { DEX: 10, CON: 5 },
  },
  Postman: {
    skills: {
      Navigate: [60, 80],
      "Drive Auto": [45, 65],
      Listen: [40, 60],
      "Spot Hidden": [40, 60],
      Stealth: [35, 55],
      "Fast Talk": [35, 55],
      Psychology: [35, 55],
      Climb: [35, 55],
      "First Aid": [30, 45],
      "Own Language": [50, 70],
    },
    credit: [15, 30],
    weapons: ["Fist"],
    statBonus: { CON: 10, DEX: 5 },
  },
  Landscaper: {
    skills: {
      "Natural World": [60, 80],
      "Sciences (Botanique)": [55, 75],
      Appraise: [40, 60],
      "Mechanical Repair": [35, 55],
      "Drive Auto": [35, 55],
      Listen: [35, 55],
      "Spot Hidden": [35, 55],
      "First Aid": [30, 45],
      Accounting: [30, 50],
      "Fast Talk": [30, 50],
    },
    credit: [15, 35],
    weapons: ["Fist"],
    statBonus: { FOR: 5, CON: 10 },
  },
  "Construction Worker": {
    skills: {
      Climb: [45, 65],
      Jump: [35, 55],
      "Mechanical Repair": [35, 55],
      "Arts et métiers (Menuiserie)": [40, 60],
      "Drive Auto": [30, 50],
      "First Aid": [35, 50],
      Dodge: [30, 45],
      "Combat. Au Contact (Corps à corps)": [30, 50],
      Throw: [30, 50],
      Listen: [30, 45],
      "Spot Hidden": [25, 40],
    },
    credit: [9, 25],
    weapons: ["Fist", "Shovel"],
    statBonus: { FOR: 10, CON: 10 },
  },
  Carpenter: {
    skills: {
      "Arts et métiers (Menuiserie)": [60, 80],
      "Mechanical Repair": [40, 60],
      Climb: [45, 65],
      Appraise: [40, 60],
      "Drive Auto": [30, 50],
      Accounting: [30, 50],
      "First Aid": [30, 45],
      "Combat. Au Contact (Haches)": [30, 50],
      Jump: [30, 45],
      "Spot Hidden": [25, 40],
    },
    credit: [20, 40],
    weapons: ["Axe"],
    statBonus: { FOR: 10, DEX: 10 },
  },
  Mason: {
    skills: {
      "Arts et métiers (Menuiserie)": [50, 70],
      Climb: [40, 60],
      "Mechanical Repair": [35, 55],
      Appraise: [40, 60],
      "Sciences (Ingénierie)": [20, 35],
      "Drive Auto": [30, 50],
      "First Aid": [30, 45],
      "Combat. Au Contact (Corps à corps)": [30, 50],
      Throw: [30, 50],
      Listen: [30, 45],
    },
    credit: [15, 35],
    weapons: ["Fist"],
    statBonus: { FOR: 10, CON: 10 },
  },
  Plumber: {
    skills: {
      "Arts et métiers (Plomberie)": [60, 80],
      "Mechanical Repair": [50, 70],
      "Electrical Repair": [30, 50],
      Climb: [35, 55],
      Appraise: [35, 55],
      "Drive Auto": [30, 50],
      Accounting: [25, 45],
      "Fast Talk": [25, 45],
      Listen: [30, 45],
      "Spot Hidden": [30, 50],
    },
    credit: [20, 40],
    weapons: ["Fist"],
    statBonus: { FOR: 5, DEX: 10 },
  },
  Architect: {
    skills: {
      "Sciences (Ingénierie)": [60, 80],
      "Arts et métiers (Beaux-arts)": [50, 70],
      Appraise: [50, 70],
      "Library Use": [45, 65],
      History: [40, 60],
      Persuade: [40, 60],
      Accounting: [40, 60],
      "Sciences (Mathématiques)": [35, 55],
      "Sciences (Physique)": [30, 50],
      Law: [30, 50],
      "Own Language": [55, 75],
    },
    credit: [45, 70],
    weapons: ["Fist"],
    statBonus: { INT: 15, EDU: 15 },
  },
  Farmer: {
    skills: {
      "Animal Handling": [50, 70],
      "Natural World": [45, 65],
      "Mechanical Repair": [40, 60],
      Survival: [45, 65],
      Navigate: [40, 60],
      "First Aid": [40, 55],
      "Drive Auto": [35, 55],
      "Combat. Arme à feu (Fusils)": [45, 65],
      Ride: [35, 55],
      Accounting: [30, 50],
      "Sciences (Botanique)": [25, 45],
      "Sciences (Zoologie)": [25, 45],
    },
    credit: [15, 40],
    weapons: ["Shotgun", "Axe"],
    statBonus: { FOR: 10, CON: 10 },
  },
  "Farm Worker": {
    skills: {
      "Animal Handling": [40, 60],
      "Natural World": [35, 55],
      Survival: [40, 60],
      "Drive Auto": [30, 50],
      Climb: [30, 50],
      "First Aid": [30, 45],
      "Combat. Au Contact (Corps à corps)": [30, 50],
      Ride: [30, 50],
      Navigate: [30, 50],
      Listen: [30, 45],
      "Spot Hidden": [25, 40],
    },
    credit: [5, 20],
    weapons: ["Fist", "Axe"],
    statBonus: { FOR: 10, CON: 10 },
  },
  "Livestock Farmer": {
    skills: {
      "Animal Handling": [60, 80],
      Ride: [55, 75],
      "Natural World": [45, 65],
      Survival: [45, 65],
      "Combat. Arme à feu (Fusils)": [45, 65],
      Navigate: [40, 60],
      "Sciences (Zoologie)": [30, 50],
      "First Aid": [35, 50],
      "Drive Auto": [30, 50],
      Accounting: [30, 50],
      Track: [30, 50],
    },
    credit: [20, 45],
    weapons: ["Shotgun", ".38 Revolver"],
    statBonus: { CON: 10, POU: 5 },
  },
  Fisherman: {
    skills: {
      Swim: [60, 80],
      "Natural World": [45, 65],
      Navigate: [50, 70],
      Survival: [50, 70],
      "Pilotage (Bateaux)": [45, 65],
      "Mechanical Repair": [35, 55],
      Climb: [35, 55],
      "Sciences (Météorologie)": [30, 50],
      "First Aid": [35, 50],
      Listen: [30, 45],
      "Spot Hidden": [30, 45],
    },
    credit: [10, 30],
    weapons: ["Knife"],
    statBonus: { FOR: 5, CON: 10, DEX: 5 },
  },
  "Police Officer": {
    skills: {
      "Combat. Arme à feu (Armes de poing)": [50, 70],
      Law: [45, 65],
      Intimidate: [45, 65],
      Psychology: [45, 65],
      "Drive Auto": [40, 60],
      Listen: [45, 65],
      "Spot Hidden": [45, 65],
      "Combat. Au Contact (Corps à corps)": [40, 60],
      Dodge: [35, 55],
      Track: [35, 55],
      "First Aid": [35, 50],
      "Fast Talk": [30, 50],
    },
    credit: [20, 40],
    weapons: [".38 Revolver", "Baton"],
    statBonus: { FOR: 5, CON: 5, POU: 5 },
  },
  Military: {
    skills: {
      "Combat. Arme à feu (Armes de poing)": [50, 70],
      "Combat. Arme à feu (Fusils)": [55, 75],
      "Combat. Au Contact (Corps à corps)": [50, 70],
      Navigate: [45, 65],
      Survival: [45, 65],
      "First Aid": [40, 60],
      Intimidate: [40, 60],
      "Drive Auto": [35, 55],
      Dodge: [40, 60],
      Listen: [40, 60],
      Throw: [35, 55],
    },
    credit: [15, 35],
    weapons: [".38 Revolver", "Shotgun"],
    statBonus: { FOR: 10, CON: 10, DEX: 5 },
  },
  "Private Detective": {
    skills: {
      "Spot Hidden": [60, 80],
      Psychology: [55, 75],
      Track: [50, 70],
      Stealth: [50, 70],
      Listen: [50, 70],
      "Library Use": [40, 60],
      Law: [40, 60],
      "Combat. Arme à feu (Armes de poing)": [40, 60],
      "Fast Talk": [40, 60],
      Charm: [35, 55],
      "Drive Auto": [35, 55],
      Locksmith: [30, 50],
      Disguise: [30, 50],
    },
    credit: [20, 45],
    weapons: [".38 Revolver"],
    statBonus: { INT: 10, POU: 5, DEX: 5 },
  },
  "BOI Agent": {
    skills: {
      Law: [55, 75],
      "Combat. Arme à feu (Armes de poing)": [55, 75],
      "Spot Hidden": [55, 75],
      Psychology: [50, 70],
      Stealth: [50, 70],
      Track: [45, 65],
      Intimidate: [45, 65],
      "Drive Auto": [45, 65],
      "Sciences (Criminalistique)": [40, 60],
      Listen: [45, 65],
      "Library Use": [40, 60],
      Locksmith: [35, 55],
      Disguise: [35, 55],
    },
    credit: [30, 55],
    weapons: [".38 Revolver", ".45 Automatic", "Thompson"],
    statBonus: { INT: 10, POU: 10, DEX: 5 },
  },
  Firefighter: {
    skills: {
      Climb: [55, 75],
      "First Aid": [55, 75],
      "Drive Auto": [45, 65],
      Jump: [45, 65],
      Dodge: [40, 60],
      "Combat. Au Contact (Haches)": [40, 60],
      "Mechanical Repair": [35, 55],
      Navigate: [35, 55],
      Listen: [35, 55],
      Swim: [40, 60],
      "Spot Hidden": [30, 50],
    },
    credit: [15, 35],
    weapons: ["Axe"],
    statBonus: { FOR: 10, CON: 15, DEX: 5 },
  },
  Paramedic: {
    skills: {
      "Drive Auto": [55, 75],
      "First Aid": [65, 85],
      Medicine: [40, 60],
      Psychology: [35, 55],
      Navigate: [40, 60],
      Listen: [40, 60],
      "Mechanical Repair": [30, 50],
      "Sciences (Biologie)": [25, 45],
      "Spot Hidden": [30, 50],
      Dodge: [30, 50],
    },
    credit: [15, 35],
    weapons: ["Fist"],
    statBonus: { DEX: 10, CON: 5 },
  },
  "Forensic Photographer": {
    skills: {
      "Arts et métiers (Photographie)": [70, 90],
      "Sciences (Criminalistique)": [55, 75],
      "Spot Hidden": [50, 70],
      Stealth: [45, 65],
      "Library Use": [40, 60],
      Psychology: [35, 55],
      Listen: [35, 55],
      Law: [30, 50],
      "Sciences (Chimie)": [30, 50],
      Appraise: [35, 55],
    },
    credit: [20, 40],
    weapons: ["Fist"],
    statBonus: { DEX: 10, INT: 10 },
  },
  "Tax Inspector": {
    skills: {
      Accounting: [65, 85],
      Law: [55, 75],
      "Library Use": [50, 70],
      Intimidate: [45, 65],
      Psychology: [40, 60],
      Persuade: [35, 55],
      "Spot Hidden": [45, 65],
      Listen: [40, 60],
      "Sciences (Mathématiques)": [40, 60],
      "Own Language": [55, 75],
    },
    credit: [30, 50],
    weapons: ["Fist"],
    statBonus: { INT: 10, EDU: 10 },
  },
  Lawyer: {
    skills: {
      Law: [70, 90],
      "Library Use": [55, 75],
      Persuade: [55, 75],
      Psychology: [50, 70],
      "Fast Talk": [50, 70],
      Charm: [40, 60],
      Intimidate: [40, 60],
      Accounting: [35, 55],
      History: [30, 50],
      "Own Language": [65, 85],
      Listen: [40, 60],
    },
    credit: [45, 75],
    weapons: ["Fist"],
    statBonus: { INT: 10, EDU: 15, APP: 5 },
  },
  Judge: {
    skills: {
      Law: [75, 95],
      Psychology: [60, 80],
      History: [50, 70],
      Intimidate: [50, 70],
      "Library Use": [55, 75],
      Persuade: [45, 65],
      Listen: [45, 65],
      "Own Language": [70, 90],
      Charm: [35, 55],
      Accounting: [30, 50],
    },
    credit: [55, 80],
    weapons: ["Fist"],
    statBonus: { INT: 15, EDU: 20, POU: 10 },
  },
  Nurse: {
    skills: {
      Medicine: [50, 70],
      "First Aid": [60, 80],
      Psychology: [45, 65],
      "Sciences (Biologie)": [35, 55],
      Listen: [40, 60],
      Persuade: [35, 55],
      "Sciences (Pharmacologie)": [30, 50],
      Charm: [30, 50],
      Stealth: [30, 50],
      "Own Language": [50, 70],
    },
    credit: [15, 35],
    weapons: ["Fist"],
    statBonus: { INT: 5, EDU: 10, POU: 5 },
  },
  Doctor: {
    skills: {
      Medicine: [65, 85],
      "First Aid": [60, 80],
      Psychology: [50, 70],
      "Sciences (Biologie)": [50, 70],
      "Library Use": [45, 65],
      "Sciences (Chimie)": [40, 60],
      "Sciences (Pharmacologie)": [45, 65],
      Persuade: [35, 55],
      "Langues (Latin)": [30, 50],
      "Own Language": [60, 80],
      Psychoanalysis: [25, 45],
    },
    credit: [50, 75],
    weapons: ["Fist"],
    statBonus: { INT: 15, EDU: 20 },
  },
  "Country Doctor": {
    skills: {
      Medicine: [60, 80],
      "First Aid": [65, 85],
      "Sciences (Biologie)": [40, 60],
      "Sciences (Pharmacologie)": [40, 60],
      Psychology: [40, 60],
      Survival: [35, 55],
      "Drive Auto": [35, 55],
      Ride: [30, 50],
      Listen: [40, 60],
      "Own Language": [55, 75],
    },
    credit: [30, 55],
    weapons: ["Fist"],
    statBonus: { INT: 10, EDU: 15, CON: 5 },
  },
  Surgeon: {
    skills: {
      Medicine: [75, 95],
      "Sciences (Biologie)": [60, 80],
      "Sciences (Pharmacologie)": [50, 70],
      "First Aid": [55, 75],
      "Sciences (Chimie)": [40, 60],
      "Library Use": [50, 70],
      Psychology: [40, 60],
      "Langues (Latin)": [35, 55],
      "Own Language": [60, 80],
      Psychoanalysis: [20, 35],
    },
    credit: [60, 85],
    weapons: ["Fist"],
    statBonus: { INT: 15, EDU: 20, DEX: 10 },
  },
  Dentist: {
    skills: {
      Medicine: [55, 75],
      "Sciences (Biologie)": [45, 65],
      "Sciences (Pharmacologie)": [40, 60],
      "First Aid": [50, 70],
      Psychology: [40, 60],
      Charm: [35, 55],
      Persuade: [30, 50],
      "Sciences (Chimie)": [30, 50],
      Accounting: [30, 50],
      "Own Language": [55, 75],
    },
    credit: [40, 65],
    weapons: ["Fist"],
    statBonus: { INT: 10, EDU: 15, DEX: 10 },
  },
  "Forensic Doctor": {
    skills: {
      Medicine: [65, 85],
      "Sciences (Biologie)": [60, 80],
      "Sciences (Criminalistique)": [55, 75],
      "Sciences (Chimie)": [45, 65],
      "Library Use": [45, 65],
      Psychology: [40, 60],
      Law: [35, 55],
      "First Aid": [45, 65],
      "Spot Hidden": [40, 60],
      "Own Language": [55, 75],
    },
    credit: [40, 65],
    weapons: ["Fist"],
    statBonus: { INT: 15, EDU: 20 },
  },
  Psychologist: {
    skills: {
      Psychology: [70, 90],
      Psychoanalysis: [60, 80],
      Persuade: [50, 70],
      Listen: [55, 75],
      "Library Use": [50, 70],
      "Fast Talk": [40, 60],
      Charm: [35, 55],
      Medicine: [30, 50],
      "Sciences (Biologie)": [25, 45],
      "Own Language": [65, 85],
      History: [30, 50],
    },
    credit: [40, 65],
    weapons: ["Fist"],
    statBonus: { INT: 15, EDU: 15, POU: 10 },
  },
  Teacher: {
    skills: {
      History: [50, 70],
      "Library Use": [55, 75],
      Psychology: [45, 65],
      Persuade: [45, 65],
      "Sciences (Mathématiques)": [40, 60],
      "Natural World": [35, 55],
      "Own Language": [60, 80],
      Charm: [35, 55],
      Listen: [40, 60],
      "Arts et métiers (Beaux-arts)": [25, 45],
    },
    credit: [15, 35],
    weapons: ["Fist"],
    statBonus: { INT: 10, EDU: 10 },
  },
  Secretary: {
    skills: {
      Accounting: [50, 70],
      "Library Use": [50, 70],
      "Own Language": [60, 80],
      Psychology: [35, 55],
      Charm: [35, 55],
      Listen: [40, 60],
      Law: [25, 45],
      Persuade: [30, 50],
      Stealth: [35, 55],
      "Spot Hidden": [30, 50],
    },
    credit: [15, 35],
    weapons: ["Fist"],
    statBonus: { EDU: 5, DEX: 5 },
  },
  Accountant: {
    skills: {
      Accounting: [65, 85],
      "Library Use": [50, 70],
      Law: [40, 60],
      Appraise: [45, 65],
      Persuade: [30, 50],
      Psychology: [30, 50],
      "Sciences (Mathématiques)": [35, 55],
      Listen: [30, 50],
      "Own Language": [55, 75],
      "Spot Hidden": [30, 50],
    },
    credit: [30, 55],
    weapons: ["Fist"],
    statBonus: { INT: 10, EDU: 10 },
  },
  Translator: {
    skills: {
      "Langues (Français)": [55, 75],
      "Langues (Allemand)": [50, 70],
      "Langues (Espagnol)": [50, 70],
      "Langues (Latin)": [45, 65],
      "Own Language": [65, 85],
      "Library Use": [50, 70],
      History: [40, 60],
      Anthropology: [35, 55],
      Listen: [40, 60],
      Persuade: [30, 50],
    },
    credit: [25, 50],
    weapons: ["Fist"],
    statBonus: { INT: 15, EDU: 15 },
  },
  Occultist: {
    skills: {
      Occult: [65, 85],
      History: [50, 70],
      "Library Use": [55, 75],
      Anthropology: [40, 60],
      Psychology: [40, 60],
      "Langues (Latin)": [40, 60],
      "Langues (Grec)": [35, 55],
      Archaeology: [30, 50],
      Hypnosis: [25, 45],
      Persuade: [30, 50],
      "Cthulhu Mythos": [5, 15],
    },
    credit: [20, 45],
    weapons: ["Fist"],
    statBonus: { INT: 10, POU: 15, EDU: 10 },
  },
  Spiritualist: {
    skills: {
      Occult: [60, 80],
      Psychology: [55, 75],
      Hypnosis: [50, 70],
      "Fast Talk": [50, 70],
      Charm: [45, 65],
      Disguise: [40, 60],
      History: [35, 55],
      "Library Use": [40, 60],
      Listen: [45, 65],
      Persuade: [40, 60],
      "Cthulhu Mythos": [3, 10],
    },
    credit: [25, 50],
    weapons: ["Fist"],
    statBonus: { POU: 15, APP: 5 },
  },
  "Fortune Teller": {
    skills: {
      Charm: [60, 80],
      "Fast Talk": [60, 80],
      Disguise: [55, 75],
      Psychology: [60, 80],
      Occult: [45, 65],
      Listen: [55, 75],
      Hypnosis: [35, 55],
      Persuade: [50, 70],
      "Spot Hidden": [40, 60],
      "Own Language": [55, 75],
    },
    credit: [15, 40],
    weapons: ["Fist"],
    statBonus: { APP: 10, POU: 10 },
  },
  Professor: {
    skills: {
      History: [55, 75],
      "Library Use": [60, 80],
      "Own Language": [65, 85],
      Psychology: [45, 65],
      Archaeology: [35, 55],
      Anthropology: [30, 50],
      Persuade: [40, 60],
      Occult: [25, 45],
      "Sciences (Mathématiques)": [40, 60],
      "Langues (Latin)": [35, 55],
      "Langues (Grec)": [25, 45],
    },
    credit: [35, 55],
    weapons: ["Fist"],
    statBonus: { INT: 15, EDU: 20 },
  },
  "Biology Researcher": {
    skills: {
      "Sciences (Biologie)": [70, 90],
      "Sciences (Chimie)": [55, 75],
      "Sciences (Botanique)": [50, 70],
      "Sciences (Zoologie)": [50, 70],
      "Library Use": [55, 75],
      "Natural World": [45, 65],
      Medicine: [35, 55],
      "Sciences (Pharmacologie)": [35, 55],
      "Langues (Latin)": [30, 50],
      "Own Language": [55, 75],
    },
    credit: [30, 55],
    weapons: ["Fist"],
    statBonus: { INT: 15, EDU: 20 },
  },
  Chemist: {
    skills: {
      "Sciences (Chimie)": [70, 90],
      "Sciences (Pharmacologie)": [55, 75],
      "Sciences (Physique)": [50, 70],
      "Sciences (Biologie)": [40, 60],
      "Library Use": [50, 70],
      Demolitions: [30, 50],
      "Sciences (Mathématiques)": [45, 65],
      "Mechanical Repair": [30, 50],
      "Langues (Allemand)": [25, 45],
      "Own Language": [55, 75],
    },
    credit: [30, 55],
    weapons: ["Fist"],
    statBonus: { INT: 15, EDU: 20 },
  },
  "Lab Technician": {
    skills: {
      "Sciences (Chimie)": [55, 75],
      "Sciences (Biologie)": [50, 70],
      "Sciences (Physique)": [40, 60],
      "Mechanical Repair": [40, 60],
      "Library Use": [45, 65],
      "Spot Hidden": [40, 60],
      "Sciences (Mathématiques)": [35, 55],
      "Natural World": [30, 50],
      Medicine: [25, 45],
      "Own Language": [50, 70],
    },
    credit: [20, 40],
    weapons: ["Fist"],
    statBonus: { INT: 10, EDU: 15, DEX: 5 },
  },
  "Academic Archaeologist": {
    skills: {
      Archaeology: [70, 90],
      History: [60, 80],
      Anthropology: [55, 75],
      "Library Use": [55, 75],
      Navigate: [45, 65],
      Climb: [40, 60],
      "Spot Hidden": [55, 75],
      Occult: [35, 55],
      "Langues (Latin)": [45, 65],
      "Langues (Grec)": [35, 55],
      "Sciences (Géologie)": [35, 55],
      Survival: [35, 55],
    },
    credit: [35, 55],
    weapons: ["Fist", ".38 Revolver"],
    statBonus: { INT: 15, EDU: 20 },
  },
  Anthropologist: {
    skills: {
      Anthropology: [70, 90],
      History: [55, 75],
      "Library Use": [55, 75],
      Listen: [50, 70],
      Psychology: [45, 65],
      "Langues (Français)": [40, 60],
      "Langues (Allemand)": [35, 55],
      "Natural World": [40, 60],
      Occult: [25, 45],
      "Own Language": [60, 80],
      Survival: [30, 50],
    },
    credit: [30, 55],
    weapons: ["Fist"],
    statBonus: { INT: 15, EDU: 20 },
  },
  Librarian: {
    skills: {
      "Library Use": [70, 90],
      History: [55, 75],
      "Own Language": [60, 80],
      "Langues (Latin)": [40, 60],
      "Langues (Grec)": [30, 50],
      Psychology: [35, 55],
      "Spot Hidden": [50, 70],
      Accounting: [35, 55],
      Occult: [25, 45],
      Persuade: [30, 50],
    },
    credit: [15, 35],
    weapons: ["Fist"],
    statBonus: { INT: 10, EDU: 20 },
  },
  Historian: {
    skills: {
      History: [75, 95],
      "Library Use": [60, 80],
      Archaeology: [45, 65],
      Anthropology: [40, 60],
      "Langues (Latin)": [50, 70],
      "Langues (Grec)": [40, 60],
      "Own Language": [65, 85],
      Occult: [25, 45],
      Persuade: [35, 55],
      Listen: [35, 55],
    },
    credit: [30, 55],
    weapons: ["Fist"],
    statBonus: { INT: 15, EDU: 25 },
  },
  Linguist: {
    skills: {
      "Langues (Latin)": [65, 85],
      "Langues (Grec)": [60, 80],
      "Langues (Français)": [55, 75],
      "Langues (Allemand)": [55, 75],
      "Langues (Espagnol)": [50, 70],
      "Langues (Italien)": [50, 70],
      "Library Use": [55, 75],
      History: [40, 60],
      Anthropology: [35, 55],
      "Own Language": [70, 90],
    },
    credit: [25, 50],
    weapons: ["Fist"],
    statBonus: { INT: 15, EDU: 25 },
  },
  Mathematician: {
    skills: {
      "Sciences (Mathématiques)": [75, 95],
      "Sciences (Physique)": [55, 75],
      "Sciences (Ingénierie)": [45, 65],
      "Sciences (Cryptographie)": [45, 65],
      "Library Use": [50, 70],
      Accounting: [50, 70],
      "Sciences (Astronomie)": [35, 55],
      "Own Language": [55, 75],
      "Langues (Allemand)": [30, 50],
      Appraise: [40, 60],
    },
    credit: [30, 55],
    weapons: ["Fist"],
    statBonus: { INT: 20, EDU: 20 },
  },
  Geographer: {
    skills: {
      Navigate: [70, 90],
      "Natural World": [55, 75],
      "Sciences (Géologie)": [50, 70],
      "Sciences (Météorologie)": [50, 70],
      "Library Use": [50, 70],
      History: [40, 60],
      "Langues (Français)": [35, 55],
      Survival: [40, 60],
      "Sciences (Botanique)": [35, 55],
      "Own Language": [60, 80],
    },
    credit: [30, 55],
    weapons: ["Fist"],
    statBonus: { INT: 15, EDU: 15 },
  },
  Archaeologist: {
    skills: {
      Archaeology: [60, 80],
      History: [55, 75],
      Anthropology: [45, 65],
      "Library Use": [50, 70],
      Navigate: [40, 60],
      Climb: [35, 55],
      "Spot Hidden": [50, 70],
      Occult: [30, 50],
      "Langues (Latin)": [35, 55],
      "Langues (Grec)": [30, 50],
      "Sciences (Géologie)": [30, 50],
      Survival: [30, 50],
    },
    credit: [35, 55],
    weapons: ["Fist", ".38 Revolver"],
    statBonus: { INT: 15, EDU: 15 },
  },
  Journalist: {
    skills: {
      "Arts et métiers (Photographie)": [45, 65],
      "Library Use": [50, 70],
      Charm: [45, 65],
      Psychology: [45, 65],
      "Fast Talk": [45, 65],
      Persuade: [40, 60],
      "Spot Hidden": [40, 60],
      History: [35, 55],
      Listen: [45, 65],
      "Own Language": [60, 80],
      "Drive Auto": [30, 50],
    },
    credit: [20, 45],
    weapons: ["Fist"],
    statBonus: { INT: 10, APP: 5 },
  },
  Photographer: {
    skills: {
      "Arts et métiers (Photographie)": [65, 85],
      Stealth: [45, 65],
      Psychology: [40, 60],
      Charm: [40, 60],
      "Fast Talk": [35, 55],
      "Spot Hidden": [45, 65],
      "Sciences (Chimie)": [30, 50],
      Listen: [35, 55],
      "Drive Auto": [30, 50],
      Appraise: [35, 55],
    },
    credit: [20, 45],
    weapons: ["Fist"],
    statBonus: { DEX: 10, APP: 5 },
  },
  Musician: {
    skills: {
      "Arts et métiers (Chant)": [55, 75],
      Charm: [50, 70],
      Psychology: [40, 60],
      Listen: [50, 70],
      "Fast Talk": [40, 60],
      Stealth: [30, 50],
      Persuade: [30, 50],
      Dodge: [30, 50],
      "Own Language": [45, 65],
      Disguise: [25, 45],
    },
    credit: [15, 40],
    weapons: ["Fist"],
    statBonus: { APP: 10, DEX: 5 },
  },
  Painter: {
    skills: {
      "Arts et métiers (Beaux-arts)": [65, 85],
      Appraise: [45, 65],
      History: [40, 60],
      "Fast Talk": [35, 55],
      Psychology: [35, 55],
      Charm: [35, 55],
      "Library Use": [35, 55],
      "Spot Hidden": [35, 55],
      Listen: [30, 50],
      Anthropology: [25, 45],
    },
    credit: [10, 40],
    weapons: ["Fist"],
    statBonus: { APP: 5, DEX: 10, INT: 5 },
  },
  Actor: {
    skills: {
      "Arts et métiers (Comédie)": [60, 80],
      Charm: [55, 75],
      Disguise: [55, 75],
      Psychology: [45, 65],
      Persuade: [45, 65],
      "Fast Talk": [45, 65],
      Intimidate: [35, 55],
      Listen: [40, 60],
      "Own Language": [55, 75],
      History: [30, 50],
    },
    credit: [20, 50],
    weapons: ["Fist"],
    statBonus: { APP: 15 },
  },
  Writer: {
    skills: {
      "Own Language": [70, 90],
      "Library Use": [55, 75],
      History: [45, 65],
      Psychology: [45, 65],
      Occult: [30, 50],
      Anthropology: [25, 45],
      Persuade: [35, 55],
      Charm: [30, 50],
      Listen: [35, 55],
      Archaeology: [20, 40],
    },
    credit: [20, 45],
    weapons: ["Fist"],
    statBonus: { INT: 10, EDU: 10 },
  },
  Businessman: {
    skills: {
      Accounting: [55, 75],
      Law: [45, 65],
      Persuade: [55, 75],
      Psychology: [50, 70],
      "Fast Talk": [50, 70],
      Charm: [45, 65],
      Intimidate: [40, 60],
      Appraise: [45, 65],
      "Own Language": [60, 80],
      "Drive Auto": [30, 50],
    },
    credit: [50, 75],
    weapons: ["Fist"],
    statBonus: { INT: 10, EDU: 10, APP: 5 },
  },
  Banker: {
    skills: {
      Accounting: [65, 85],
      Law: [50, 70],
      Appraise: [55, 75],
      Persuade: [45, 65],
      Psychology: [45, 65],
      "Library Use": [40, 60],
      Charm: [40, 60],
      "Fast Talk": [35, 55],
      "Own Language": [60, 80],
      "Sciences (Mathématiques)": [35, 55],
    },
    credit: [55, 80],
    weapons: ["Fist"],
    statBonus: { INT: 10, EDU: 15 },
  },
  Politician: {
    skills: {
      Charm: [55, 75],
      Persuade: [60, 80],
      Psychology: [55, 75],
      Law: [45, 65],
      "Fast Talk": [55, 75],
      Intimidate: [40, 60],
      History: [40, 60],
      Listen: [40, 60],
      "Own Language": [65, 85],
      Disguise: [35, 55],
    },
    credit: [50, 75],
    weapons: ["Fist"],
    statBonus: { APP: 10, POU: 10, INT: 5 },
  },
  Industrialist: {
    skills: {
      Accounting: [55, 75],
      Law: [45, 65],
      Persuade: [50, 70],
      Intimidate: [50, 70],
      Psychology: [45, 65],
      "Sciences (Ingénierie)": [35, 55],
      "Mechanical Repair": [30, 50],
      Appraise: [45, 65],
      "Own Language": [55, 75],
      "Fast Talk": [40, 60],
    },
    credit: [60, 85],
    weapons: ["Fist"],
    statBonus: { INT: 10, POU: 10 },
  },
  "Wealthy Heir": {
    skills: {
      Charm: [55, 75],
      "Fast Talk": [50, 70],
      Psychology: [40, 60],
      Appraise: [45, 65],
      History: [40, 60],
      "Langues (Français)": [35, 55],
      "Langues (Allemand)": [30, 50],
      Ride: [40, 60],
      Accounting: [30, 50],
      Persuade: [40, 60],
    },
    credit: [75, 98],
    weapons: ["Fist"],
    statBonus: { APP: 10, EDU: 10 },
  },
  Bootlegger: {
    skills: {
      "Drive Auto": [55, 75],
      Intimidate: [50, 70],
      "Fast Talk": [50, 70],
      "Combat. Arme à feu (Armes de poing)": [45, 65],
      Stealth: [45, 65],
      "Mechanical Repair": [40, 60],
      Navigate: [40, 60],
      Psychology: [35, 55],
      Dodge: [35, 55],
      Accounting: [30, 50],
    },
    credit: [25, 50],
    weapons: [".45 Revolver", "Baton"],
    statBonus: { DEX: 10, POU: 5 },
  },
  Bookmaker: {
    skills: {
      Accounting: [55, 75],
      "Fast Talk": [50, 70],
      Psychology: [50, 70],
      Intimidate: [40, 60],
      Stealth: [40, 60],
      Listen: [45, 65],
      Persuade: [35, 55],
      "Sciences (Mathématiques)": [30, 50],
      "Spot Hidden": [35, 55],
      Dodge: [30, 50],
    },
    credit: [30, 55],
    weapons: ["Fist", ".32 Revolver"],
    statBonus: { INT: 10 },
  },
  Henchman: {
    skills: {
      "Combat. Au Contact (Corps à corps)": [55, 75],
      Intimidate: [55, 75],
      "Combat. Arme à feu (Armes de poing)": [50, 70],
      "Drive Auto": [40, 60],
      Stealth: [40, 60],
      Dodge: [45, 65],
      Listen: [40, 60],
      Track: [35, 55],
      "Spot Hidden": [35, 55],
      Throw: [35, 55],
    },
    credit: [15, 35],
    weapons: [".45 Revolver", "Baton", "Brass Knuckles"],
    statBonus: { FOR: 15, CON: 10 },
  },
  Prostitute: {
    skills: {
      Charm: [55, 75],
      Psychology: [55, 75],
      "Fast Talk": [50, 70],
      Stealth: [45, 65],
      Listen: [50, 70],
      Pickpocket: [35, 55],
      Dodge: [40, 60],
      Disguise: [35, 55],
      "First Aid": [30, 50],
      "Spot Hidden": [35, 55],
    },
    credit: [10, 30],
    weapons: ["Knife", "Razor"],
    statBonus: { APP: 10 },
  },
  Smuggler: {
    skills: {
      "Drive Auto": [50, 70],
      "Pilotage (Bateaux)": [45, 65],
      Stealth: [50, 70],
      Navigate: [50, 70],
      "Combat. Arme à feu (Armes de poing)": [40, 60],
      "Fast Talk": [40, 60],
      Intimidate: [35, 55],
      "Mechanical Repair": [35, 55],
      Swim: [35, 55],
      Dodge: [35, 55],
    },
    credit: [25, 50],
    weapons: [".38 Revolver"],
    statBonus: { DEX: 10 },
  },
  Hitman: {
    skills: {
      "Combat. Arme à feu (Armes de poing)": [65, 85],
      "Combat. Arme à feu (Fusils)": [55, 75],
      Stealth: [60, 80],
      Track: [50, 70],
      "Drive Auto": [45, 65],
      Locksmith: [40, 60],
      Dodge: [50, 70],
      "Spot Hidden": [45, 65],
      Intimidate: [40, 60],
      Psychology: [35, 55],
    },
    credit: [30, 55],
    weapons: [".45 Revolver", "Rifle", "Knife"],
    statBonus: { DEX: 15, INT: 5 },
  },
  Capo: {
    skills: {
      Intimidate: [60, 80],
      Psychology: [55, 75],
      "Combat. Arme à feu (Armes de poing)": [50, 70],
      Accounting: [45, 65],
      Law: [40, 60],
      "Fast Talk": [50, 70],
      Persuade: [40, 60],
      "Drive Auto": [35, 55],
      Listen: [45, 65],
      "Own Language": [55, 75],
    },
    credit: [45, 70],
    weapons: [".45 Revolver", ".45 Automatic"],
    statBonus: { POU: 10, INT: 10 },
  },
  "Crime Boss": {
    skills: {
      Intimidate: [65, 85],
      Psychology: [60, 80],
      Persuade: [60, 80],
      Accounting: [50, 70],
      Law: [50, 70],
      "Fast Talk": [55, 75],
      History: [35, 55],
      Charm: [40, 60],
      "Own Language": [60, 80],
      "Langues (Italien)": [45, 65],
    },
    credit: [70, 95],
    weapons: ["Fist"],
    statBonus: { POU: 20, INT: 10, APP: 5 },
  },
  Housewife: {
    skills: {
      "Arts et métiers (Cuisine)": [50, 70],
      "First Aid": [45, 65],
      Psychology: [40, 60],
      Charm: [35, 55],
      Listen: [45, 65],
      Accounting: [35, 55],
      "Fast Talk": [30, 50],
      Persuade: [35, 55],
      "Spot Hidden": [40, 60],
      "Animal Handling": [25, 45],
    },
    credit: [15, 35],
    weapons: ["Fist"],
    statBonus: { POU: 5 },
  },
  Student: {
    skills: {
      "Library Use": [45, 65],
      "Own Language": [50, 70],
      History: [35, 55],
      "Sciences (Mathématiques)": [30, 50],
      Psychology: [30, 50],
      Listen: [35, 55],
      Charm: [30, 50],
      "Fast Talk": [30, 50],
      Jump: [30, 50],
      Dodge: [30, 50],
    },
    credit: [10, 25],
    weapons: ["Fist"],
    statBonus: { EDU: 5 },
  },
  Unemployed: {
    skills: {
      "Fast Talk": [35, 55],
      Stealth: [35, 55],
      Listen: [40, 60],
      "Spot Hidden": [40, 60],
      Dodge: [30, 50],
      Psychology: [30, 50],
      Pickpocket: [25, 45],
      Survival: [25, 45],
      Climb: [30, 50],
      "Combat. Au Contact (Corps à corps)": [25, 45],
    },
    credit: [1, 10],
    weapons: ["Fist"],
    statBonus: {},
  },
  Retiree: {
    skills: {
      History: [45, 65],
      Listen: [50, 70],
      Psychology: [45, 65],
      "Library Use": [40, 60],
      "First Aid": [40, 60],
      "Own Language": [55, 75],
      Persuade: [35, 55],
      "Natural World": [35, 55],
      "Spot Hidden": [40, 60],
      Appraise: [40, 60],
    },
    credit: [15, 45],
    weapons: ["Fist"],
    statBonus: {},
  },
};
